#!/bin/bash
# Parallel Blitz - Daily Report Generation

echo "📈 PARALLEL BLITZ - DAILY REPORT"
echo "================================="
echo ""

DATE=$(date '+%Y-%m-%d')
REPORT_DIR="/root/.openclaw/workspace/parallel-blitz/reports/daily"
mkdir -p "$REPORT_DIR"

REPORT_FILE="$REPORT_DIR/$DATE.md"

cat > "$REPORT_FILE" << EOF
# Parallel Blitz Daily Report
**Date:** $DATE
**Sprint Day:** Day $(echo $(($(date +%s) - $(date -d "2026-03-26" +%s)) / 86400 + 1))

## Overall Metrics

| Metric | Today | Sprint Total | Goal | % to Goal |
|--------|-------|--------------|------|-----------|
| Leads | 0 | 0 | 160 | 0% |
| Conversions | 0 | 0 | - | - |
| Revenue | \$0 | \$0 | \$1,025 | 0% |

## Business Breakdown

EOF

# Add business details
for i in {1..6}; do
    BIZ_DIR="/root/.openclaw/workspace/parallel-blitz/businesses/biz-$i"
    
    echo "### Business $i" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    
    if [ -f "$BIZ_DIR/config.json" ]; then
        NAME=$(cat "$BIZ_DIR/config.json" | grep -o '"name": "[^"]*"' | cut -d'"' -f4)
        MODEL=$(cat "$BIZ_DIR/config.json" | grep -o '"model": "[^"]*"' | cut -d'"' -f4)
        echo "**Name:** $NAME" >> "$REPORT_FILE"
        echo "**Model:** $MODEL" >> "$REPORT_FILE"
    fi
    
    if [ -f "$BIZ_DIR/metrics.json" ]; then
        LEADS=$(cat "$BIZ_DIR/metrics.json" | grep -o '"leads": [0-9]*' | cut -d' ' -f2)
        CONV=$(cat "$BIZ_DIR/metrics.json" | grep -o '"conversions": [0-9]*' | cut -d' ' -f2)
        REV=$(cat "$BIZ_DIR/metrics.json" | grep -o '"revenue": [0-9.]*' | cut -d' ' -f2)
        
        echo "**Leads:** ${LEADS:-0}" >> "$REPORT_FILE"
        echo "**Conversions:** ${CONV:-0}" >> "$REPORT_FILE"
        echo "**Revenue:** \$${REV:-0}" >> "$REPORT_FILE"
    else
        echo "*Metrics not yet tracked*" >> "$REPORT_FILE"
    fi
    
    echo "" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << EOF
## Top Performers

1. TBD
2. TBD
3. TBD

## Underperformers (Action Required)

- TBD

## Cross-Business Learnings

- TBD

## Tomorrow's Focus

- TBD

## Resource Allocation

Current allocation: Equal across all 6 businesses
Recommended: TBD based on performance

---
*Generated by Parallel Blitz System*
EOF

echo "✅ Report generated: $REPORT_FILE"
echo ""
echo "Preview:"
head -30 "$REPORT_FILE"
